"""add deadline_at and duration_seconds

Revision ID: 7d093d52e81e
Revises: df501a4accdb
Create Date: 2026-08-02 03:03:42.947855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d093d52e81e'
down_revision: Union[str, Sequence[str], None] = 'df501a4accdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('deadline_at')

    # ### end Alembic commands ###
